# Generated by Django 4.2.2 on 2024-07-09 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_producto_adquisicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.IntegerField()),
                ('fecha_uso', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.producto')),
            ],
        ),
    ]
