# Generated by Django 4.2.2 on 2024-07-09 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usoproducto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usoproducto',
            options={'ordering': ['-fecha_uso']},
        ),
        migrations.AlterField(
            model_name='usoproducto',
            name='fecha_uso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
